### ISSUE TITLE
Видимо баг нашел.

### ISSUE THREAD

**Issue by makbeth** [himiklab/yii2-sortable-grid-view-widget#10]
Точно не уверен, что это баг, но у меня на пердыдущем проекте ваше расширение работает отлично, а на текущем нет. Проблема с отправкой данных на серврер. Перетаскивание строк работает, но при перетаскивании строки выскакивает ошибка "error Bad Request" в алерте. Причем видимо проблема именно во view. Сделал точно так как написано в инструкции, перепроверил по старому проекту - все идентично, но не работает. Стал смотреть html старого проекта и сравнивать с новым. Нашел, что у рабочего проекта в строки таблицы добавляются классы такого вида: <tr data-key="4" class="items[]_4 ui-sortable-handle"><td style="width:50px; text-align:center">
А в новом проекте почему-то не добавляются классы типа items[]_4. На сколько могу судить, то из-за этого на сервер уходит запрос вида: items	{"2":"4","4":"5","5":"2"}, но на рабочем проекте на сервер данные уходят вот в таком виде (взято из firebug): 
items[]	4
items[]	5
items[]	2
items[]	1
items[]	3

Подскажите, в чем может быть дело? А если все же это баг вашего расширения, то как скоро сможете его исправить? Заранее спасибо.

**Comment by himiklab** [comment]
Здравствуйте.
Просто у Вас на старом проекте стабильная версия, а на новом dev, в последнем коммите я внёс некоторые изменения в алгоритм работы.

Можете просто подключить стабильную версию или давайте разберёмся что за ошибка, в том-же фаербаге должны быть подробности. Не проходит запрос, т. ч. скорее всего проблема где-то у Вас в конфигурации.

**Comment by makbeth** [comment]
Давайте попробуем разобраться, в чем может быть дело. Возможно эта проблем не только у меня появится. В фаербаге в ответе только это: Bad Request (#400): Не удалось проверить переданные данные. Смею предположить, что серверная часть ожидает данные в ином виде, но может проблема и не в этом, если ваши изменения затронули формат, в котором должны уходить данные. По поводу проблемы с конфигурацией. Где вы думаете она может быть?

**Comment by himiklab** [comment]
Проверьте, есть ли в заголовке запроса поле `X-CSRF-Token`.\
http://yiiframework.ru/forum/viewtopic.php?t=18474

**Comment by makbeth** [comment]
Да. В этом было дело. Огромное вам спасибо! Извените, что отнял ваше время

**Comment by himiklab** [comment]
Рад помочь!
