### ISSUE TITLE
Calling unknown method: app\models\[ModelName]::tableName()

### ISSUE THREAD

**Issue by kaynewilder** [himiklab/yii2-sortable-grid-view-widget#15]
Please help me. 

I am getting this error:
**Calling unknown method: app\models\PayrollItems::tableName()**

in C:\wamp3\www\iaoy-sprobe-svn\vendor\himiklab\yii2-sortable-grid-view-widget\SortableGridBehavior.php – yii\base\Component::__call('tableName', [])

Line 74
`$maxOrder = $model->find()->max($model->tableName() . '.' . $this->sortableAttribute);`

Here's my `actions` in my controller:
````
    public function actions()
    {
        return [
            'sort' => [
                'class' => SortableGridAction::className(),
                'modelName' => PayrollItems::className(),
                // 'tableName' => 'payroll_items',
            ],
        ];
    }
````
Model:
````
    public function behaviors()
    {
        return [
            'sort' => [
                'class' => SortableGridBehavior::className(),
                'sortableAttribute' => 'sortOrder',
                // 'query' => self::find(),
            ],
        ];
    }
````
GridView:
````
    <?php echo SortableGridView::widget([
        'dataProvider' => $dataProvider,
       // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
        	'code_type',
        	'payroll_name',
            [   
                'label' => 'Action',    
                'content' => function ($model, $key, $index, $column) {
                if ( ($model->company_id != null) && ($model->active == 1) ) { 
            	    if(in_array($model->payroll_name, array("CPF", "SINDA", "MENDAKI", "FWL", "SDL", "CDAC", "ECF", "MBMF", "Union Fund", "Insurance", "Unpaid Leave","Deductions", "NSMen Pay"))){
                        return Html::button('<span class="glyphicon glyphicon-eye-open"></span>', ['value' => Url::to(['view-deduction']).'&id=' . (string)$model->_id, 'class' => 'btn btn-warning btn-view btn-responsive','id' => 'modalButton2']);
                    } else {
                        return Html::button('<span class="glyphicon glyphicon-eye-open"></span>', ['value' => Url::to(['view-deduction']).'&id=' . (string)$model->_id, 'class' => 'btn btn-warning btn-view btn-responsive','id' => 'modalButton2'])
                        .'&nbsp'
                        . Html::button('<span class="glyphicon glyphicon-pencil"></span>', ['value' => Url::to(['update-deduction']).'&id=' . (string)$model->_id, 'class' => 'btn btn-success btn-view btn-responsive','id' => 'modalButton3'])
                        .'&nbsp'
                        . Html::a('<span class="glyphicon glyphicon-remove"></span>', ['delete-deduction', 'id' => (string)$model->_id], ['class' => 'btn btn-danger btn-responsive', 'data' => ['confirm' => 'Are you sure you want to delete this deduction item?', 'method' => 'post']])
                        .'&nbsp'
                        . Html::button('Unset as Default', ['value' => (string)$model->_id, 'class' => 'btn btn-danger btn-responsive', 'onclick'=>'unset(value)']);
                        }
                    } else {
                         return Html::button('<span class="glyphicon glyphicon-eye-open"></span>', ['value' => Url::to(['view-deduction']).'&id=' . (string)$model->_id, 'class' => 'btn btn-warning btn-view btn-responsive','id' => 'modalButton2'])
                        .'&nbsp'
                        . Html::button('<span class="glyphicon glyphicon-pencil"></span>', ['value' => Url::to(['update-deduction']).'&id=' . (string)$model->_id, 'class' => 'btn btn-success btn-view btn-responsive','id' => 'modalButton3'])
                        .'&nbsp'
                        . Html::a('<span class="glyphicon glyphicon-remove"></span>', ['delete-deduction', 'id' => (string)$model->_id], ['class' => 'btn btn-danger btn-responsive', 'data' => ['confirm' => 'Are you sure you want to delete this deduction item?', 'method' => 'post']])
                        .'&nbsp'
                        . Html::button('Set as Default', ['value' => (string)$model->_id, 'class' => 'btn btn-info btn-responsive', 'onclick'=>'set(value)']);
                    }
                }
            ]
        ],
        'sortableAction' => Yii::$app->request->baseUrl . '/index.php?r=payroll-items/deduction-index'
    ]); ?>
````

The dragging works fine and all but in my view, I have "Create Deduction Item" button (located above the GridView) where it will show a modal for creation of a deduction item and whenever I click "Save", it will generate that error.

The widget didn't have enough info so I'm really having a hard time on what to do.

I'm looking forward for your response and help.

**Comment by himiklab** [comment]
Add in your model:
```
public static function tableName()
{
    return 'payroll_items';
}
```

**Comment by kaynewilder** [comment]
Yes! Thank you so much, it worked! :)

**Comment by RyoAizaki** [comment]
please help me
this site is getting error

Unknown Method – yii\base\UnknownMethodException
Calling unknown method: app\models\SimakMastermahasiswa::hitungIPK()
1. in /var/www/html/siakad/_protected/vendor/yiisoft/yii2/base/Component.phpat line 301
292293294295296297298299300301302303304305306307308309310     */
    public function __call($name, $params)
    {
        $this->ensureBehaviors();
        foreach ($this->_behaviors as $object) {
            if ($object->hasMethod($name)) {
                return call_user_func_array([$object, $name], $params);
            }
        }
        throw new UnknownMethodException('Calling unknown method: ' . get_class($this) . "::$name()");
    }
 
    /**
     * This method is called after the object is created by cloning an existing one.
     * It removes all behaviors because they are attached to the old object.
     */
    public function __clone()
    {
        $this->_events = [];
2. in /var/www/html/siakad/themes/klorofil/views/site/index.php at line 348– yii\base\Component::__call('hitungIPK', [])
342343344345346347348349350351352353354          </div>
        </div>  
        <div class="col-md-6">
          <div class="metric">
            <span class="icon"><i class="fa fa-user"></i></span>
            <p>
              <span class="number"><?=round($mhs->hitungIPK(),2);?></span>
              <span class="title">IPK</span>
            </p>
 
            <p>
              <span class="number"><?=$mhs->SKSLulus;?></span>
              <span class="title">Total SKS Lulus</span>
3. in /var/www/html/siakad/_protected/vendor/yiisoft/yii2/base/View.php at line 348– require('/var/www/html/siakad/themes/klor...')
4. in /var/www/html/siakad/_protected/vendor/yiisoft/yii2/base/View.php at line 257– yii\base\View::renderPhpFile('/var/www/html/siakad/themes/klor...', ['tahfidz' => null, 'mhs' => app\models\SimakMastermahasiswa, 'indukKegiatan' => [app\models\SimakIndukKegiatan, app\models\SimakIndukKegiatan, app\models\SimakIndukKegiatan], 'fakultas' => [], ...])
5. in /var/www/html/siakad/_protected/vendor/yiisoft/yii2/base/View.php at line 156– yii\base\View::renderFile('/var/www/html/siakad/themes/klor...', ['tahfidz' => null, 'mhs' => app\models\SimakMastermahasiswa, 'indukKegiatan' => [app\models\SimakIndukKegiatan, app\models\SimakIndukKegiatan, app\models\SimakIndukKegiatan], 'fakultas' => [], ...], app\controllers\SiteController)
6. in /var/www/html/siakad/_protected/vendor/yiisoft/yii2/base/Controller.php at line 410– yii\base\View::render('index', ['tahfidz' => null, 'mhs' => app\models\SimakMastermahasiswa, 'indukKegiatan' => [app\models\SimakIndukKegiatan, app\models\SimakIndukKegiatan, app\models\SimakIndukKegiatan], 'fakultas' => [], ...], app\controllers\SiteController)
7. in /var/www/html/siakad/_protected/controllers/SiteController.php at line 820– yii\base\Controller::render('index', ['tahfidz' => null, 'mhs' => app\models\SimakMastermahasiswa, 'indukKegiatan' => [app\models\SimakIndukKegiatan, app\models\SimakIndukKegiatan, app\models\SimakIndukKegiatan], 'fakultas' => [], ...])
814815816817818819820821822823824825826            'ta' => $ta,
            'count_mhs' => $results2,
            'count_krs' => $results1,
            'list_kampus' => $list_kampus,
            'tagihan' => $tagihan,
 
            'list_tahun' => $list_tahun
        ]);
 
    }
 
    public function actionAjaxRincianTagihan()
    {
8. app\controllers\SiteController::actionIndex()
9. in /var/www/html/siakad/_protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57– call_user_func_array([app\controllers\SiteController, 'actionIndex'], [])
10. in /var/www/html/siakad/_protected/vendor/yiisoft/yii2/base/Controller.php at line 181– yii\base\InlineAction::runWithParams([])
11. in /var/www/html/siakad/_protected/vendor/yiisoft/yii2/base/Module.php at line 534– yii\base\Controller::runAction('index', [])
12. in /var/www/html/siakad/_protected/vendor/yiisoft/yii2/web/Application.php at line 104– yii\base\Module::runAction('site/index', [])
13. in /var/www/html/siakad/_protected/vendor/yiisoft/yii2/base/Application.php at line 392– yii\web\Application::handleRequest(yii\web\Request)
14. in /var/www/html/siakad/index.php at line 12– yii\base\Application::run()
6789101112 
require(__DIR__ . '/_protected/vendor/autoload.php');
require(__DIR__ . '/_protected/vendor/yiisoft/yii2/Yii.php');
 
$config = require(__DIR__ . '/_protected/config/web.php');
 
(new yii\web\Application($config))->run();
$_COOKIE = [
    'PHPSESSID' => 'kor6jilp9upidaeulkjuhjma52',
    '_csrf' => '369b663413cc86bc841207be15a5f5eee111629ad4cde603cc921d756422d127a:2:{i:0;s:5:"_csrf";i:1;s:32:"-21IjWhKtbfO4hbrrLYvdxVHGOkOJBBY";}',
];

$_SESSION = [
    '__flash' => [],
    'token' => 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvY2VudHJhbC51bmlkYS5nb250b3IuYWMuaWRcLyIsInN1YiI6InNlYW55YWdvemFAdW5pZGEuZ29udG9yLmFjLmlkIiwidXVpZCI6IjUyMDMzMjM4LTgzMzgtNGJhZS1iNDBkLTBmMGRkZjY4NzVmYiIsIm5hbWUiOiJCaXNtYSBZYWdvemEiLCJlbWFpbCI6InNlYW55YWdvemFAdW5pZGEuZ29udG9yLmFjLmlkIiwiaWF0IjoxNjMyOTIwNDU1LCJleHAiOjE2Mzk0MDA0NTUsImFwcHMiOlt7ImFwcF9pZCI6MSwiYXBwX25hbWUiOiJTSUFLQUQiLCJhcHBfdXJsIjoiaHR0cHM6XC9cL3NpYWthZC51bmlkYS5nb250b3IuYWMuaWRcL3NpdGVcL2xvZ2luLXNzbz90b2tlbj0ifSx7ImFwcF9pZCI6MTMsImFwcF9uYW1lIjoiV0lTVURBIiwiYXBwX3VybCI6Imh0dHBzOlwvXC93aXN1ZGEudW5pZGEuZ29udG9yLmFjLmlkXC9pbmRleC5waHA_cj1zaXRlXC9sb2dpblNzbyZ0b2tlbj0ifV19.QdwqB8G87dWP30U-w2c5O2VCg2lyc2NfpYtaTXhYvnw',
    'tahun_id' => '20211',
    '__id' => 31049,
    '__authKey' => 'eZuSGxelxlWzegJrOA7BsOWvBHDT5xtG',
];

**Comment by Emad980** [comment]
Emadshammout893@gmail.com
