### ISSUE TITLE
Order not saved if models has null value for sortableAttribute

### ISSUE THREAD

**Issue by nick-denry** [himiklab/yii2-sortable-grid-view-widget#29]
Hi!

In case of $model->sortableAttribute set to null, $orderValue is the same after swap for both models and updateAttributes changes nothing.

https://github.com/himiklab/yii2-sortable-grid-view-widget/blob/a4a7ba529e0de33c69c403a907251d51b7f902bd/SortableGridBehavior.php#L65

I've created pull request for this.

**Comment by nick-denry** [comment]
Related https://github.com/himiklab/yii2-sortable-grid-view-widget/issues/13

**Comment by himiklab** [comment]
Hello!
``$model->sortableAttribute`` must not be null. For what it may be necessary?

**Comment by nick-denry** [comment]
> Hello!
$model->sortableAttribute must not be null. For what it may be necessary?

In case of we add sortableAttribute column for existing table eg. "sort_order" via migration, whether sortableAttribute is notNull or null all column values will be the same:

1:0
2:0
etc...
or 
1: null,
2: null
etc...

Issue is presented in both cases, cause attributes wont be updated via updateAttributes (getDirtyAttributes not triggered).

**Comment by himiklab** [comment]
Merged!
Thanks!
