### ISSUE TITLE
Composite primary key causes a UnknownPropertyException

### ISSUE THREAD

**Issue by arstar** [himiklab/yii2-sortable-grid-view-widget#8]
When applying the SortableGridView to a model with a composite primary key, the id is not recognized.
I would like to suggest using the data-key that is stored in each row instead of the items[]_#. This stores a json array with the keys and columnames when a composite PK is used.

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-sortable-grid-view-widget/pull/9
